#!/bin/sh

dafny="/Users/nudzhang/installations/dafny/dafny /timeLimit:20 /compile:0 /allowGlobals /vcsCores:8 /noNLarith"

files="../lib/UtilitiesLibrary.dfy types.dfy hosts.dfy distributedSystem.dfy spec.dfy messageInvariants.dfy"

echo "Verifying $files"

time $dafny $files