#!/bin/sh

echo "Verifying centralized"
cd centralized
./verify
cd - > /dev/null
echo ""

echo "Verifying decentralized"
cd decentralized
./verify
cd - > /dev/null
echo ""

echo "Verifying decentralizedMonotonic"
cd decentralizedMonotonic
./verify
cd - > /dev/null
echo ""

echo "Verifying automate"
cd automate
./verify-auto
cd - > /dev/null
echo ""