#!/bin/sh

dafny="/Users/nudzhang/installations/dafny-3.5.0/Scripts/dafny /timeLimit:20 /compile:0 /allowGlobals /vcsCores:8 /noNLarith"

files="../../lib/UtilitiesLibrary.dfy hosts.dfy distributedSystem.dfy spec.dfy proof.dfy"

echo "Verifying $files"

time $dafny $files