#!/bin/sh

echo "Verifying centralized"
cd centralized
./verify
cd -
echo ""

echo "Verifying centralizedMonotonic"
cd centralizedMonotonic_globalHistory
./verify
cd - 
echo ""

echo "Verifying decentralized"
cd decentralized
./verify
cd - 
echo ""

echo "Verifying decentralizedMonotonic"
cd decentralizedMonotonic_globalHistory
./verify
cd - 
echo ""
