#!/bin/sh

echo "Verifying centralized"
cd centralized
./verify
cd - > /dev/null
echo ""

echo "Verifying centralizedMonotonic"
cd centralizedMonotonic
./verify
cd - > /dev/null
echo ""

echo "Verifying decentralizedMonotonic"
cd decentralizedMonotonic
./verify
cd - > /dev/null
echo ""

echo "Verifying decentralizedMonotonicTemplated"
cd decentralizedMonotonicTemplated
./verify
cd - > /dev/null
echo ""

echo "Verifying automate"
cd automate
./verify-auto
cd - > /dev/null
echo ""
