#!/bin/sh

if uname -a | grep -q Darwin; then
    dafny="/Users/nudzhang/installations/dafny-3.5.0/Scripts/dafny /timeLimit:20 /compile:0 /allowGlobals /vcsCores:8 /noNLarith"
elif uname -a | grep -q Linux; then
    dafny="/home/nudzhang/dafny/dafny /timeLimit:20 /compile:0 /allowGlobals /vcsCores:8 /noNLarith"
else
    echo "Failed"
    exit 1
fi

files="../../lib/UtilitiesLibrary.dfy types.dfy hosts.dfy"

echo "Verifying $files"

time $dafny $files