#!/bin/sh

dafny="/Users/nudzhang/Documents/UMich2023sp/linear-dist.nosync/local-dafny/Scripts/dafny /timeLimit:20 /compile:0  /noNLarith /autoTriggers:1 /vcsCores:10"

files="../../lib/UtilitiesLibrary.dfy hosts.dfy distributedSystem.dfy spec.dfy messageInvariants.dfy applicationProof.dfy"

echo "Verifying $files"

time $dafny $files