#!/bin/sh

dafnyMsgInv="/Users/nudzhang/Documents/UMich2023sp/linear-dist.nosync/local-dafny/Scripts/dafny /msgInvs"
dafnyAsyncProof="/Users/nudzhang/Documents/UMich2023sp/linear-dist.nosync/local-dafny/Scripts/dafny /genAsyncProof"
dafnyVerify="/Users/nudzhang/Documents/UMich2023sp/linear-dist.nosync/local-dafny/Scripts/dafny /timeLimit:20 /compile:0  /noNLarith /autoTriggers:1 /vcsCores:10"

rm -f messageInvariantsAutogen.dfy monotonicityInvariantsAutogen.dfy applicationProofDraftAutogen.dfy

# Generate Message Invariants and Monotonicity Invariants
$dafnyMsgInv "distributedSystem.dfy" > autoInvs.log

# Generate Async proof draft
$dafnyAsyncProof "../centralized/applicationProof.dfy" > autoProof.log

# Verify files. In this case, the draft is good enough
echo "Verifying $files"
files="../../lib/* ../hosts.dfy ../types.dfy distributedSystem.dfy spec.dfy monotonicityInvariantsAutogen.dfy messageInvariantsAutogen.dfy applicationProofDraftAutogen.dfy"

# time $dafnyVerify $files