#!/bin/sh

dafny="/Users/nudzhang/installations/dafny-4.2.0/dafny /timeLimit:20 /compile:0  /noNLarith /autoTriggers:1 /vcsCores:10"

files="../../lib/UtilitiesLibrary.dfy ../hosts.dfy distributedSystem.dfy spec.dfy messageInvariantsAutogen.dfy applicationProof.dfy"

rm -f messageInvariantsAutogen.dfy
python3 ../../python-parser/parser.py ../hosts.dfy > messageInvariantsAutogen.dfy

echo "Verifying $files"

time $dafny $files