#!/bin/sh

dafnyMsgInv="/Users/nudzhang/Documents/UMich2023sp/linear-dist.nosync/local-dafny/Scripts/dafny /msgInvs /ownerInvs"
dafnyVerify="/Users/nudzhang/Documents/UMich2023sp/linear-dist.nosync/local-dafny/Scripts/dafny /timeLimit:20 /compile:0  /noNLarith /autoTriggers:1 /vcsCores:10"

files="../../lib/* ../types.dfy ../hosts.dfy distributedSystem.dfy spec.dfy messageInvariantsAutogen.dfy ownershipInvariantsAutogen.dfy applicationProof.dfy"

rm -f *Autogen.dfy
$dafnyMsgInv "distributedSystem.dfy" > autoInvs.log

echo "Verifying $files"

time $dafnyVerify $files