#!/bin/sh

dafny="/Users/nudzhang/installations/dafny-4.2.0/dafny /timeLimit:20 /compile:0 /vcsCores:12 /noNLarith"

files="../../lib/UtilitiesLibrary.dfy types.dfy hosts.dfy distributedSystem.dfy spec.dfy messageInvariants.dfy applicationProof.dfy"

echo "Verifying $files"

time $dafny $files